name: Build Java PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew clean build

      - name: Upload built program
        uses: actions/upload-artifact@v4
        with:
          name: java-pr-build
          path: |
            build/libs/*.jar
